### ISSUE TITLE
[不具合]UIが正常に表示されない

### ISSUE THREAD

**Issue by yuhkan** [infiniteloop-inc/crystal-signal#11]
環境：Raspberry pi3 
OS：Raspbian Stretch Lite(Kernel 4.9、Release 2017-09-07)
ブラウザ：Firefox、Internet Explorer、Edge(スクリーンショットはFirefoxのもの)

(前回記載のDocker関係とは別口です)

1：Micro SDXCカードにOSをインストール
2：boot下に「ssh」ファイルを置いてssh有効化
3：sshでログイン
4：readme記載に従い、install.shをDL
5：「install.sh fullinstall」実行
　の実行後、ブラウザでのアクセスを行ったところ、スクリーンショットの状態になります(再現性有り、3回試して3回とも)
　タイトルは 「<?php echo LABEL_TITLE ?>」となっています。
スライダーのドラッグ、ボタンの押下は可能で、ドラッグ実施で点滅は制御されているように見えます。
![screenshot-2017-11-26 php echo label_title](https://user-images.githubusercontent.com/7992278/33267391-a999bf7e-d3bc-11e7-8d48-3e46d8c11b09.png)

　過去、5月頃提供されていたリリースを利用していたときは、特に問題は発生していませんでした。

**Comment by 8yazaki** [comment]
Raspbianの標準レポジトリがPHP７に変更になったのですが、ミドルウエアのインストールではPHP5をインストールしようとしてエラーになってしまっているみたいです。

私の場合は、
1.RaspbianOSのインストール
2.パッケージ、OSディストリビュージョンのアップグレード
3.ファームウェアのアップグレード
4.Crystal Signal Piのミドルウェアインストール
5.PHP7のインストール(sudo apt-get install php)
6.Crystal Signal Piのミドルウェアをフルインストール

で問題なく表示・動作されるようになりました。

**Comment by T-Kuhn** [comment]
報告をありがとうございます！
現在確認中です。

**Comment by T-Kuhn** [comment]
8yazakiさんが指摘してくださったように、PHP5をダウンロードしようとしたときにパッケージが見つからなくて、結局PHPが正常にインストールされないのが問題でした。

![php5notavailable](https://user-images.githubusercontent.com/14211994/33301715-a4ef332c-d43a-11e7-8785-f09827633c29.PNG)

ご指摘、ありがとうございます。
install.shを更新しました。
https://github.com/infiniteloop-inc/crystal-signal/commit/cce96c81c35d3be49f58fe6f8cf6eca428366c16

**Comment by T-Kuhn** [comment]
JessieとStretchでインストールすべきPHPのパッケージが異なるため、挙動をOSのバージョンによって分ける必要があることが判明し、さらにinstall.shを更新しました。
https://github.com/infiniteloop-inc/crystal-signal/commit/96bd860d941b50fe61238a72535088dfe665a355

**Comment by T-Kuhn** [comment]
更新したinstall.shをjessieとstretchで確認済みです。これでphpが正しくインストールされるはずなのでissueを閉じます。
