### ISSUE TITLE
UIのレスポンシブ化

### ISSUE THREAD

**Issue by 8yazaki** [infiniteloop-inc/crystal-signal#13]
UIをスマホからアクセスすると、部分的に横幅が長く横スクロールが表示されてしまい操作しずらい状態です。
CSSの変更だけなので以前は自前で修正していたのですが、アップデートする度に都度修正が必要になってしまうため、レスポンシブ表示を公式サポートしてほしいです。

**Comment by T-Kuhn** [comment]
お、これは前にも聞いた話です。Issue登録をありがとうございます！
8YazakiさんからCSS修正済みバージョンでPull Requestをしていただければ話が一番早いと思いますが、PRの有無を問わず改善すべきところとして認識しています。近いうちに調べてみたいと思います。

**Comment by 8yazaki** [comment]
自前で修正したCSSは別ファイルで作成し、各PHPファイルの</head>直前で読み込ませるようにして適用していました。

細かな部分やスライダーの操作性などまだ修正したほうがいい箇所もあるかもしれませんが、私が作成しましたCSSを参考までにこちらに貼らせていただきます。

====================

@media screen and (max-width: 479px) {
.block1,.block2,.buttonBox,.sliderBox {
  max-width: 600px;
  width: 100%;
  margin-left: 0;
}
.innerInputBox {
  max-width: 400px;
  width:100%;
}
.innerButtonBox1 {
  width: 100%;
}
.innerButtonBox2 {
  margin: 0;
}
.slider.slider-horizontal {
  margin-left: 15px;
}
.boxLeft {
  margin-left: 0;
}
.tooltip.top {
  display: none;
}
.panel-body {
  padding: 10px;
}

.table {
  border
}
.table th {
  background-color:#000;
  color: #fff;
  font-weight: bold;
}
.table td,.table th {
  float: left;
  display: block;
  width: 20%;
  height:80px;
  word-wrap: break-word;
  
}
}

====================

**Comment by T-Kuhn** [comment]
参考にしたいと思います。共有をありがとうございます！

**Comment by T-Kuhn** [comment]
なるほど。現在の状態だとこうなりますねー…
![smartphonecrystalsignalpi](https://user-images.githubusercontent.com/14211994/33409450-c6621378-d5be-11e7-9143-cfca38bde2b5.PNG)

**Comment by T-Kuhn** [comment]
8yazakiさんのコードを利用しmasterを更新させていただきました。

**Comment by T-Kuhn** [comment]
https://github.com/infiniteloop-inc/crystal-signal/releases/tag/1.5
GUIの改善の余地はまだまだあるかと思いますが、このissueはこれでcloseいたします。
