### ISSUE TITLE
JSONでの取得を試みると、Internal Server Errorとなる

### ISSUE THREAD

**Issue by yuhkan** [infiniteloop-inc/crystal-signal#14]
環境：Raspberry pi3
OS：Raspbian Stretch Lite(Kernel 4.9、Release 2017-09-07)
ソフト：最新版(11/28版)ミドルウェア

　題記の通りですが、オプション"json"を1にすると、Internal Server Errorが返ります。

例：Python3.5コンソールより

> >import requests
> >uri = "http://＜addr＞/ctrl/?color=100,80,0&mode=0&repeat=0&period=1000&json=1"
> >res = requests.get(uri)
> >print(res)
> 
> <Response [500]>  ←レスポンス

> >print(res.text)
>
> '&lt;!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"&gt;\n&lt;html&gt;&lt;head&gt;\n&lt;title&gt;500 Internal Server Error&lt;/title&gt;\n&lt;/head&gt;&lt;body&gt;\n&lt;h1&gt;Internal Server Error&lt;/h1&gt;\n&lt;p&gt;The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.&lt;/p&gt;\n&lt;p&gt;Please contact the server administrator at \n webmaster@localhost to inform them of the time this error occurred,\n and the actions you performed just before this error.&lt;/p&gt;\n&lt;p&gt;More information about this error may be available\nin the server error log.&lt;/p&gt;\n&lt;hr&gt;\n&lt;address&gt;Apache/2.4.25 (Raspbian) Server at 192.168.88.17 Port 80&lt;/address&gt;\n&lt;/body&gt;&lt;/html&gt;\n'

　設定のuriは、UI上の「アラート実行コマンド」に表示されるコマンドの引き写しで、UI上ではレスポンスが正しく返っているようですが、ブラウザで上記コマンドを直接コピペしても、Internal Server Errorとなります。
　なお、点滅自体は指定の通りに動作しているように見えます。また、json=0の場合、レスポンスは200が返っています

**Comment by T-Kuhn** [comment]
報告をありがとうございます！
明日確認します。

**Comment by T-Kuhn** [comment]
問題が現在のクリシグミドルウエアを使用し、OSがjessieとstretch、どちらでも再現できました。調べ中。

**Comment by T-Kuhn** [comment]
修正しました。
原因：
2017年6月に、controller.pyを整理し、JSONの場合、サーバ返事に"Content-type: text/html \n\n"が不要と間違って判断してしまいました。

**Comment by T-Kuhn** [comment]
```
$ curl -O https://raw.githubusercontent.com/infiniteloop-inc/crystal-signal/master/install.sh
$ sudo bash install.sh update
```
で直るかと思います。問題なくJSONデータが取れることが確認できたらissueのcloseをお願いします。

**Comment by yuhkan** [comment]
修正が行われたことを確認しました(Stretch)。
迅速な対応をありがとうございます。
