### ISSUE TITLE
[不具合？] json=1のときの挙動が説明と異なる

### ISSUE THREAD

**Issue by yuhkan** [infiniteloop-inc/crystal-signal#17]
「README_JAPANESE.md」の、『APIからの操作方法』によると、パラメータ"json"の説明では、

<blockquote>
json=1を指定すると、現在のCrystal Signal Piの状態をJSONフォーマットで返します。この際、他のパラメータはすべて無視されます。シェルスクリプト等から副作用なしに、現在の状態を取得するためのパラメータです。
</blockquote>

　とありますが、

> http://192.168.88.17/ctrl/?color=0,255,0&mode=0&repeat=0&period=1000&json=1

　とブラウザから送信したり、pythonからrequests.get()したりしたばあい、
・シグナルが点灯する(パラメータが無視されていない)
・戻り値は<pre>{"info": "", "ack": 0, "json": 1, "repeat": 0, "mode": 0, "remote_addr": "192.168.88.2", "color": [0, 255, 0], "remote_host": 0, "period": 1000, "speak": ""} </pre>
 　となる(「現在の状態」ではなく、変更された後の状態の取得)

　と、取説内容と大きく異なるようです。
(前回の時に気づいていれば良かったような気もしますが……)

・この場合、誤っているのは取説でしょうか、処理でしょうか？
・"json=1"「のみ」指定の場合、現在状態が返っているようですが、これはそれで正常でしょうか？
・取説の指定を正とする場合、「点灯を制御したうえで、返値はJSONとする」(=現在のjson=1の状態)が存在しない事になりますが、このときその手段は「json=0で点灯制御のうえ、json=1で改めて状態取得」という事になるのでしょうか？

　確認をお願いします。

**Comment by T-Kuhn** [comment]
ご指摘をありがとうございます！
これは説明と挙動が合いませんね。
確認・修正しますー。

**Comment by T-Kuhn** [comment]
現在の基本的な挙動：
- colorパラメータを含んだリクエスト送信　→　クリスタルシグナル・Piに新たなアラートが登録されて、状態が変わる（colorパラメータがアラート発生のための必要条件）。
- 送信に対する返答はjson=0の場合はHTML、json=1の場合はJSON形式。

yuhkanさんのいう通り、新たなアラートを発生させずに現在状態を取得したい場合は「json=1」のみでリクエストを送信するとよい。

今の挙動で不都合がないと思います。ドキュメントが間違っているのはご指摘の通りなので修正します！
