### ISSUE TITLE
[質問]Raspberry Pi 4での動作(他)

### ISSUE THREAD

**Issue by yuhkan** [infiniteloop-inc/crystal-signal#20]
お世話になっております。

題記の通りになるのですが、
・Raspberry Pi 4 Model B
・Raspberry pi 3 Model B+
　での、Crystal Signal Piの動作(最新OSでの動作検証)は、どのようになっていますでしょうか？

　新規の増設を検討しており、最新のハード、OSでの動作状況について、確認したく思います。

(2017年11月から24h365d通電で使用中のCrystal Signal Piは、2年超の間不具合等をおこすことも無く、正常動作を続けています。大変良いハードウェアをありがとうございます)

**Comment by infiniteloop-sapporo** [comment]
yuhkan さん

弊社製品をご愛顧いただきありがとうございます。

Crystal Signal Pi での動作に関するご質問についてですが、現在は
Raspberry Pi 4 Model B では Raspbian Buster で動作することが確認できております。
Raspberry Pi 3 Model B+ では動作未確認となっております。

**Comment by yuhkan** [comment]
infiniteloop-sapporo 様

　返信をありがとうございます。
Raspberry Pi 4 Model B  での動作確認済みとのことで、了解しました。

　合わせて、２点確認させてください。
1. Amazonでは、現状通常盤のみの販売で、残数が表示されている状態になっていますが、こちらはまだ販売継続中(終売ではない)という理解で大丈夫でしょうか？

2. 本製品用ミドルウェアは、2018年のアップデート以降(その必要が無かったのも大きいと思いますが)動きが無い形となっています。
  ミドルウェアについて、今後のRaspbianの更新への対応など、(最低で)いつくらいまでサポートがあると思っておけばよいでしょうか？
 
　よろしくお願いします。

**Comment by infiniteloop-sapporo** [comment]
yuhkan さん

ご質問いただいた2点の回答になります。

Q1. Amazonでは、現状通常盤のみの販売で、残数が表示されている状態になっていますが、こちらはまだ販売継続中(終売ではない)という理解で大丈夫でしょうか？

A1. はい。一時的に在庫切れになることはありますが、今後も販売を継続する予定でございます。

Q2. 本製品用ミドルウェアは、2018年のアップデート以降(その必要が無かったのも大きいと思いますが)動きが無い形となっています。
ミドルウェアについて、今後のRaspbianの更新への対応など、(最低で)いつくらいまでサポートがあると思っておけばよいでしょうか？

A2. 最低でも2021年まではサポートを行う予定となっており、
それ以降も具体的な期間は定めておりませんが、大きな仕様変更などサポートが困難にならない限りは継続する予定でおります。

**Comment by yuhkan** [comment]
infiniteloop-sapporo 様

返信をありがとうございます。
このようなとても良いハードウェアが、長くサポートされることに感謝します。
