### ISSUE TITLE
サウンド出力の実装希望

### ISSUE THREAD

**Issue by juzumaru** [infiniteloop-inc/crystal-signal#3]
光と同時にアラーム音がサウンド出力から出せるようにして欲しい。
そうすれば完全に警子ちゃん・パトライトの代わりになるんですが・・・。

**Comment by infiniteloop-sapporo** [comment]
現在、アラート発生時やボタン押下時に、ユーザーが作成した任意のスクリプトを実行させる機能の追加を検討しています。
これにより、アラート発生時にaplayコマンドでwaveファイルを再生する、等の挙動を追加することが可能になると考えています。

**Comment by juzumaru** [comment]
おお！
確かに任意のスクリプト実行の方が良いですね。
色々使えそう。
実装楽しみに待ってます。

**Comment by T-Kuhn** [comment]
次バージョン基板（Raspberry Pi Zero W用になりそう）で小型スピーカーを追加し、音出力を可能にしたいと考えています。それまでは現在クリスタルシグナル・Piのスクリプト機能を利用してaplayを通して音を出すのが有力な手でしょう。
